"""Add leader_id to team

Revision ID: ee6bb1a4bb4c
Revises: 2b3c4d5e6f7g
Create Date: 2026-08-05 16:49:23.488832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ee6bb1a4bb4c'
down_revision: Union[str, Sequence[str], None] = '2b3c4d5e6f7g'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team', sa.Column('leader_id', sa.Uuid(), nullable=True))
    op.alter_column('team', 'problem_statement_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_foreign_key(None, 'team', 'user', ['leader_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'team', type_='foreignkey')
    op.alter_column('team', 'problem_statement_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('team', 'leader_id')
    # ### end Alembic commands ###
